### ISSUE TITLE
samsung_slsi?

### ISSUE THREAD

**Issue by ripee** [Haxynox/seals_something_anotherhing#2]
https://github.com/Haxynox/seals_something_anotherhing/blob/a94fcf210bae5a3a28b455e8740e300803d56eb9/hero-common.mk#L106

Shouldn't it be samsung_slsi-cm for this line and the one below it? ;) @ivanmeler

**Comment by ivanmeler** [comment]
No, This is private source and it doesnt use samsung_slsi-cm but BSP source for 8890 which cant be shared publically due to licensing, You can find precompiled binaries from that repository at https://github.com/ivanmeler/proprietary_vendor_seal tho

**Comment by ivanmeler** [comment]
Github went in derp mode ignore this
